//
// Created by Edot on 2023/10/10.
//

#ifndef EXP_CPP_INCLUDE_ERROR_TYPE_H_
#define EXP_CPP_INCLUDE_ERROR_TYPE_H_

enum Error{
    REDEFINED,
    UNDEFINED,
    PARAM_COUNT_MISMATCH,
    PARAM_TYPE_MISMATCH,
    RETURN_MISMATCH,
    RETURN_MISSING,
    ASSIGN_TO_CONST,
    FORMAT_MISMATCH,
    SEMICOLON_MISSING,
    PARENT_MISSING,
    BRACKET_MISSING,
    BREAK_CONTINUE_ERROR,
    ILLEGAL_FORMAT
};
typedef enum Error Error;

#endif //EXP_CPP_INCLUDE_ERROR_TYPE_H_
